name: Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      # Passo para instalar dependências Python
      - name: Install Python dependencies
        run: |
          if [ -f ./src/requirements.txt ]; then
            python3 -m venv venv
            source venv/bin/activate
            pip install -r ./src/requirements.txt
          fi

      # Passo para empacotar a Lambda em um arquivo ZIP
      - name: Create ZIP file for Lambda
        run: |
          mkdir -p lambda
          cp -r ./src/* lambda/
          cd lambda
          zip -r lambda_function.zip .
          cd ..

      # Verificar se o arquivo ZIP foi criado
      - name: Check if ZIP file exists
        run: |
          if [ ! -f lambda/lambda_function.zip ]; then
            echo "ZIP file not found!"
            exit 1
          fi

      # Terraform Init
      - name: Terraform Init
        run: terraform init
        working-directory: ./infra

      # Terraform Validate
      - name: Terraform Validate
        run: terraform validate
        working-directory: ./infra

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Passo para importar os recursos existentes para o estado do Terraform
      - name: Terraform Import (IAM Role)
        run: |
          terraform import aws_iam_role.lambda_role lambda_execution_role || true
          terraform import aws_iam_policy.lambda_cognito_policy lambda_cognito_policy || true
        working-directory: ./infra

      # Terraform Refresh
      - name: Terraform Refresh
        run: terraform refresh -input=false
        working-directory: ./infra

      # Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./infra

      # Get Lambda function name from Terraform output
      - name: Get Lambda function name from Terraform output
        id: lambda_name
        run: echo "::set-output name=lambda_function_name::$(terraform output -raw lambda_function_name)"

      # Subir a função Lambda
      - name: Upload Lambda ZIP to AWS
        run: |
          echo "Updating Lambda function ${LAMBDA_FUNCTION_NAME}"
          aws lambda update-function-code \
            --function-name ${{ steps.lambda_name.outputs.lambda_function_name }} \
            --zip-file fileb://lambda/lambda_function.zip \
            --region ${{ secrets.AWS_REGION }}
