name: Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        working-directory: ./infra

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./infra

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Export environment variables
        run: |
          echo "TF_VAR_aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "TF_VAR_region=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV
          echo "TF_VAR_table_name=cliente" >> $GITHUB_ENV

      - name: Terraform Refresh
        run: terraform refresh -input=false
        working-directory: ./infra

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./infra

      # Novo passo para instalar dependências Python
      - name: Install Python dependencies
        run: |
          # Verifica se o requirements.txt existe na pasta src e instala as dependências
          if [ -f ./src/requirements.txt ]; then
            python3 -m venv venv
            source venv/bin/activate
            pip install -r ./src/requirements.txt
          fi

      # Novo passo para empacotar a Lambda em um arquivo ZIP
      - name: Create ZIP file for Lambda
        run: |
          mkdir -p lambda_package
          cp -r ./src/* ./lambda_package  # Copia o código fonte da Lambda para a pasta temporária
          cd lambda_package
          zip -r lambda_function.zip .  # Empacota tudo em um arquivo .zip

      # Novo passo para enviar o arquivo ZIP para a função Lambda
      - name: Upload Lambda ZIP to AWS
        run: |
          aws lambda update-function-code \
            --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
            --zip-file fileb://lambda_package/lambda_function.zip \
            --region ${{ secrets.AWS_REGION }}
